# Generated by Django 4.2.4 on 2023-09-06 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('sector', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.policestation')),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('deployment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.sector')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.shift')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
