# Generated by Django 4.2.4 on 2023-09-07 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_account_rank_alter_account_role_and_more'),
        ('deployments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='deployments.sector'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='deployments.shift'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.policestation'),
        ),
    ]
