# Generated by Django 4.2.4 on 2023-09-07 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('deployments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.policestation'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='deployments.sector'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='deployments.shift'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
