# Generated by Django 4.2.4 on 2023-09-08 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deployments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='users',
            field=models.ManyToManyField(related_name='deployments', to=settings.AUTH_USER_MODEL),
        ),
    ]
