# Generated by Django 4.2.4 on 2023-09-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0004_deployment_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
