# Generated by Django 4.2.4 on 2023-09-07 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loggings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='SubjectStatus',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='status',
            new_name='subject_status',
        ),
        migrations.RenameField(
            model_name='subjectstatus',
            old_name='status',
            new_name='subject_status',
        ),
    ]
