# Generated by Django 4.2.4 on 2023-09-09 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loggings', '0002_logging_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logging',
            old_name='time',
            new_name='log_time',
        ),
        migrations.AddField(
            model_name='logging',
            name='log_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
