# Generated by Django 4.2.4 on 2023-09-09 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loggings', '0004_logging_previous_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='PIN',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='PIN_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loggings.pintype'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loggings.subjectstatus'),
        ),
    ]
