# Generated by Django 4.2.4 on 2023-09-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loggings', '0006_alter_logging_previous_log_alter_logging_tencode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logging',
            name='current_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='logging',
            name='destination_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='logging',
            name='details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='logging',
            name='log_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='logging',
            name='log_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
