# Generated by Django 4.2.4 on 2023-09-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loggings', '0008_alter_logging_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logging',
            name='log_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='logging',
            name='log_time',
            field=models.TimeField(),
        ),
    ]
