# Generated by Django 4.2.4 on 2023-09-07 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.rank'),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.role'),
        ),
        migrations.AlterField(
            model_name='account',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.policestation'),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.division'),
        ),
    ]
